SOURCES = [
    # Threat Intelligence & Research
    {"name": "Krebs on Security",       "url": "https://krebsonsecurity.com/feed/"},
    {"name": "Schneier on Security",    "url": "https://www.schneier.com/feed/atom/"},
    {"name": "The Hacker News",         "url": "https://feeds.feedburner.com/TheHackersNews"},
    {"name": "BleepingComputer",        "url": "https://www.bleepingcomputer.com/feed/"},
    {"name": "Dark Reading",            "url": "https://www.darkreading.com/rss.xml"},
    {"name": "SecurityWeek",            "url": "https://feeds.feedburner.com/securityweek"},
    {"name": "Threatpost",              "url": "https://threatpost.com/feed/"},
    {"name": "Recorded Future",         "url": "https://www.recordedfuture.com/feed"},
    {"name": "Mandiant Blog",           "url": "https://www.mandiant.com/resources/blog/rss.xml"},
    {"name": "Google Project Zero",     "url": "https://googleprojectzero.blogspot.com/feeds/posts/default"},
    {"name": "Talos Intelligence",      "url": "https://blog.talosintelligence.com/feeds/posts/default"},
    {"name": "Rapid7 Blog",             "url": "https://www.rapid7.com/blog/rss/"},
    {"name": "Malwarebytes Labs",       "url": "https://www.malwarebytes.com/blog/feed/"},
    {"name": "Sophos News",             "url": "https://news.sophos.com/en-us/feed/"},
    {"name": "SANS Internet Storm",     "url": "https://isc.sans.edu/rssfeed_full.xml"},
    {"name": "CISA Advisories",         "url": "https://www.cisa.gov/cybersecurity-advisories/all.xml"},
    {"name": "US-CERT",                 "url": "https://www.cisa.gov/uscert/ncas/alerts.xml"},
    {"name": "NVD CVE Feed",            "url": "https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml"},
    {"name": "Cyber Scoop",             "url": "https://cyberscoop.com/feed/"},
    {"name": "ZDNet Security",          "url": "https://www.zdnet.com/topic/security/rss.xml"},
    {"name": "Ars Technica Security",   "url": "https://feeds.arstechnica.com/arstechnica/security"},
    {"name": "Troy Hunt Blog",          "url": "https://www.troyhunt.com/rss/"},
    {"name": "NCSC UK",                 "url": "https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml"},
]
